In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
smp_df = pd.read_csv("../data/smp_courses.csv")
onde_df = pd.read_csv("../data/ondemand_courses.csv")
we_df = pd.read_csv("../data/we_courses.csv")
panya_df = pd.read_csv("../data/panya_courses.csv")
physicsbp_df = pd.read_csv("../data/physicsblueprint_courses.csv")

In [3]:
df = pd.concat([smp_df, onde_df, we_df, panya_df, physicsbp_df], ignore_index=True)
df.shape

(443, 10)

In [4]:
print(df['institute_name'].value_counts(normalize=True) * 100)

institute_name
WE By The Brain      35.891648
SmartMathPro         29.119639
Panya Society        16.930023
Physics Blueprint    10.158014
OnDemand              7.900677
Name: proportion, dtype: float64

In [5]:
df.head()

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
0,SmartMathPro,PACK คณิต ม.6 เทอม 1+2 + พิชิตคณิตพื้นฐาน ม.6 ...,พี่ปั้น SmartMathPro,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),143.0,5650.0,39.51,https://online.smartmathpro.com/product/e043/
1,SmartMathPro,PACK A-Level ไทย-สังคม (V.เต็ม),"อ.ขลุ่ย, ครูกอล์ฟ",อื่นๆ,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),121.0,3390.0,28.02,https://online.smartmathpro.com/product/p021/
2,SmartMathPro,PACK TPAT1 (ครบ 3 พาร์ต) + A-Level คณิต 1 (V.เ...,"พี่ปั้น SmartMathPro, อ.ขลุ่ย, พี่หมออู๋",Mixed,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),433.0,12350.0,28.52,https://online.smartmathpro.com/product/c029/
3,SmartMathPro,PACK TPAT3 (V.เต็ม) + A-Level คณิต 1 (V.เต็ม) ...,"พี่ปั้น SmartMathPro, อ.ขลุ่ย, พี่หนู, พี่ฟาร์...",Mixed,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),628.0,21390.0,34.06,https://online.smartmathpro.com/product/r027/
4,SmartMathPro,PACK A-Level คณิต 2 (V.เต็ม) + ปรับพื้นคณิตพิช...,พี่ปั้น SmartMathPro,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),86.0,3350.0,38.95,https://online.smartmathpro.com/product/d048/

In [6]:
df.isna().sum()

institute_name     0
course_name        0
tutor              6
subject            0
course_type        0
learning_format    0
total_hours        0
price              0
price_per_hour     0
url                0
dtype: int64

In [7]:
df[df['tutor'].isna()]

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
133,OnDemand,Davance: คอร์ส TURBO สรุป ไทย+สังคม,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์/สาขา),74.0,5200.0,70.27,https://shoponline.ondemand.in.th/20021803.html
153,OnDemand,Pack จับคู่ UpSkill 2 วิชา (เลข ฟิสิกส์),NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),90.0,6900.0,76.67,https://shoponline.ondemand.in.th/20024149cv.html
155,OnDemand,Pack กลุ่มอะตอม ตารางธาตุ และพันธะเคมี,NaN,เคมี,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),84.5,4300.0,50.89,https://shoponline.ondemand.in.th/20014059cv.html
330,Panya Society,คอร์สเตรียมสอบ A,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),24.0,5000.0,208.33,https://panyasociety.com/course/preview/16
385,Panya Society,● TGAT Eng + A-Level Eng ●,NaN,Mixed,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),24.0,5000.0,208.33,https://panyasociety.com/course/preview/65
395,Panya Society,คอร์สเตรียมสอบ A,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),24.0,5000.0,208.33,https://panyasociety.com/course/preview/116

In [19]:
mask = df['course_name'] == '● TGAT Eng + A-Level Eng ●'
df.loc[mask, ['tutor', 'price']] = ['ครูพี่ตวง', 2490]
df.loc[mask, 'price_per_hour'] = df.loc[mask, 'price'] / df.loc[mask, 'total_hours']

mask = df['url'] == 'https://panyasociety.com/course/preview/16'
df.loc[mask, ['subject','tutor', 'price', 'course_name']] = ['ภาษาไทย','ครูพี่ชาร์ป', 2490, 'คอร์สเตรียมสอบ Alevel ภาษาไทย']
df.loc[mask, 'price_per_hour'] = df.loc[mask, 'price'] / df.loc[mask, 'total_hours']

mask = df['url'] == 'https://panyasociety.com/course/preview/116'
df.loc[mask, ['subject','tutor', 'price', 'course_name']] = ['สังคมศึกษา','ครูพี่ณุณิ', 2490, 'คอร์สเตรียมสอบ Alevel สังคมศึกษา']
df.loc[mask, 'price_per_hour'] = df.loc[mask, 'price'] / df.loc[mask, 'total_hours']

In [20]:
mask = df['url'] == 'https://shoponline.ondemand.in.th/20021803.html'
df.loc[mask, ['tutor', 'subject']] = ['อาจารย์ปิง', 'Mixed']

mask = df['url'] == 'https://shoponline.ondemand.in.th/20024149cv.html'
df.loc[mask, ['tutor', 'subject']] = ['พี่แท็ป พี่เต้ย พี่เกรท', 'Mixed',]

mask = df['url'] == 'https://shoponline.ondemand.in.th/20014059cv.html'
df.loc[mask, ['tutor', 'subject']] = ['พี่เคน', 'เคมี',]

In [22]:
df.isna().sum()

institute_name     0
course_name        0
tutor              0
subject            0
course_type        0
learning_format    0
total_hours        0
price              0
price_per_hour     0
url                0
dtype: int64